version: 1.1.0
services:
  - php:
      version: 8.3
variables:
  global:
    JOB_URL: "https://cloud.acquia.com/app/develop/applications/${PIPELINE_APPLICATION_ID}/pipelines/jobs/${PIPELINE_JOB_ID}"
    COMMIT_URL: "https://bitbucket.org/web_ops/optimum-mobile/commits/${PIPELINE_GIT_HEAD_REF}"
events:
  build:
    steps:
      - build-js-app:
          type: script
          script:
            - echo 'STARTED at' $(date)
            - nvm install v14.19.1
            - nvm use v14.19.1
            - cd $SOURCE_DIR
            - npm install gulp-cli@^3.0.0 -g && gulp --version
            - echo 'FINISHED at' $(date)
      - composer-install:
          type: script
          script:
            # Build non-development composer packages.
            - echo 'STARTED at' $(date)
            - echo 'Composer command'
      - lint:
          type: script
          script:
            - echo 'STARTED at' $(date)
            - cd $SOURCE_DIR
            - mkdir -p docroot/themes/custom/mobile/slice
            - cd docroot/themes/custom/mobile/slice
            - gulp --version
            - echo 'FINISHED at' $(date)
