version: 1.2.0

services:
  - php:
      version: 8.2

events:
  build:
    steps:
      - script1:
          script: 
            - composer --version
            - ls /mnt/tmp/local.prod
      
      - setup:
          script:
            - echo "Starting build..."
            - php --version
            - composer --version
      
      - install:
          script:
            - echo "Installing Composer dependencies..."
            - echo "Installation completed!"
            - echo "Build process finished."
      - build-artifact:
            type: script
            script:
              - git status
              - git diff
              - mkdir /tmp/acli-push-artifact
              - acli -vvv push:artifact --no-push --no-clone --no-commit
