version: 1.3.0

services:
  - composer:
      version: 2

events:
  build:
    steps:
      - script1:
          script:
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 30
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 30
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 30
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 30
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 30
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 30
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 5
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 5
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 5
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 5
          - printf '%*s' 8000000 '' | tr ' ' 'X'
          - sleep 5
          - printf '%*s' 8000000 '' | tr ' ' 'X'
