version: 1.0.0
services:
  - mysql

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - mysql --version
            - mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE test_db;"
