version: 1.0.0
services:
  - mysql

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - touch somefile.txt
            - chmod +x somefile.txt
            - mysql --version
            - mysql -u root -proot -e "SHOW VARIABLES LIKE '%vers%'"
