version: 1.0.0
services:
  - php:
      version: 8.2

events:
  build:
    steps:
      - composer_setup:
          type: script
          script:
            - composer --version
            - node -e "require('crypto').createHash('md5').update('')" || echo 'Node md5 is not supported in FIPS mode.'
            - php -r 'echo md5("foo");' || 'PHP md5 is not working.'
            - sleep 5
      - deploy:
          type: deploy
          script:
            - echo "Running deployment script"
            - sleep 5
  post-deploy:
    steps:
      - deploy_to_acquia:
          type: deploy
          script:
            - echo "Deploying to Acquia"
      - sync_databases:
          type: script
          script:
            - echo "Database sync completed"
