version: 1.3.0
services:
  - composer:
      version: 2
  - mysql
  - php:
      version: 8.3

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
    SIMPLETEST_DB: "mysql://root:root@localhost/drupal"
events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer install --ansi
              - composer audit
              - chmod +x vendor/bin/drush
              - composer update drush/drush
              - mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"
              - nvm install 22.15.0
              - node -v
              - npm -v
              - nvm list
              - ls docroot/themes/custom
              - google-chrome --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 &
              - sleep 2
              - echo "=== Chrome Process Check ==="
              - pgrep -a -f chrome || echo "No Chrome processes found"
              - echo "=== End Chrome Check ==="
        - validate:
            type: script
            script:
              # - php -d memory_limit=-1 ${COMPOSER_BIN}/composer drupal:validate
              - composer drupal:validate
        - setup-app:
            type: script
            script:
              - composer drupal:install      

        - build-artifact:
            type: script
            script:
              - export PATH=${COMPOSER_BIN}:${PATH}
              - mkdir /tmp/acli-push-artifact
              - git status
              - acli push:artifact --no-push --no-clone --no-commit
              - ls /tmp/acli-push-artifact/docroot/themes/custom/members_only/js/
              - cp -a docroot/themes/custom/members_only/js/. /tmp/acli-push-artifact/docroot/themes/custom/members_only/js/
              - ls /tmp/acli-push-artifact/docroot/themes/custom/members_only/js/
              - shopt -s dotglob && rm -rf ./* && mv /tmp/acli-push-artifact/* ./
